---

- name: check the package
  command: dpkg-query -W {{ item.name }}
  register: deb_exists

- name: fetch deb
  get_rul:
	url={{ item.url }}
  	dest="/tmp/{{ item.name }}.deb"   
  when: deb_exists.rc == 1

- name: install deb
  apt: deb="/tmp/{{ item.name }}.deb"
  when: deb_exists.rc == 1
