---

- name: basic dev tools
  apt: name={{ item }} state=present
  with_items:
    - emacs24-nox
    - build-essential
    - ack-grep
    - terminator
    - libssl-dev
    - libffi-dev
    - libcurl4-openssl-dev
    - git

## ===== Docker
- name: install docker
  shell: curl -fsSL https://get.docker.com/ | sh
  tags: docker_build

- name: add to ubuntu
  shell: usermod -aG docker ubuntu
  tags: docker_build

- name: install pip
  shell: wget -O - https://bootstrap.pypa.io/get-pip.py | python -

- name: pkgs in pip
  pip: name={{ item }} state=present
  with_items:
    - ansible
    - boto
    - docker-compose
    - jupyter
    - docker-py
