---

- name: basic dev tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - emacs24-nox
    - build-essential
    - ack-grep
    - terminator
    - libssl-dev
    - libffi-dev
    - libcurl4-openssl-dev
    - git
    - python-dev

## ===== Docker
- name: install docker
  shell: "curl -fsSL https://get.docker.com/ | sh"
  tags: docker_build

- name: add to user
  shell: usermod -aG docker {{ ansible_ssh_user }}
  tags: docker_build

- name: install pip
  shell: wget -O - https://bootstrap.pypa.io/get-pip.py | python -

- name: pkgs in pip
  pip: name={{ item }} state=present
  with_items:
    - ansible
    - boto
    - docker-compose
    - docker-py

- name: create folder
  sudo: no
  file: path="{{ item }}" state=directory
  with_items:
    - "~/.ssh"
    - "~/.aws"
  tags: key_copy

- name: cp keys
  sudo: no
  copy: src="{{ item.src }}" dest="{{ item.dest }}" mode=0600
  with_items:
    - {src: "~/.ssh/id_rsa", dest: "~/.ssh/"}
    - {src: "~/.ssh/id_rsa.pub", dest: "~/.ssh/"}
    - {src: "~/.aws/credentials", dest: "~/.aws"}
    - {src: "~/.aws/config", dest: "~/.aws"}
  tags: key_copy

#- name: config file
#  include: config.yml
#  tags: config


- name: install deb pkg
  include: deb.yml
  with_items:
    - {{ name: "vagrant", url: "https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb"}}
